name: 'olist_wh_transform'
version: '1.0.0'
profile: 'transform'

# different types of dbt files 
# this is relative to where `dbt run` is run
model-paths: ["transform/models"]
analysis-paths: ["transform/analyses"]
test-paths: ["transform/tests"]
seed-paths: ["transform/seeds"]
macro-paths: ["transform/macros"]
snapshot-paths: ["transform/snapshots"]

# directories to be removed by `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# Specifies sink file type and schema for each model (specified by folder)
# These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro e.g. {{ config(materialized='table') }}
# Config indicated by + and applies to all files under models/staging/
models:
  olist_wh_transform:    # must match the `name:` in this file
    staging:             # must match the folder names in models
      +materialized: view
      +schema: stg
    intermediate:
      +schema: int
      +materialized: view
    marts:
      +schema: marts
      +materialized: table      # or incremental for large tables

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
