name: 'transform'
version: '1.0.0'
config-version: 2

profile: 'transform'

model-paths: ["transform/models"]
analysis-paths: ["transform/analyses"]
test-paths: ["transform/tests"]
seed-paths: ["transform/seeds"]
macro-paths: ["transform/macros"]
snapshot-paths: ["transform/snapshots"]

target-path:  "target"
clean-targets: ["target", "dbt_packages"]

vars:
  uncategorised_label: 'uncategorised'

models:
  transform:
    staging:
      +materialized: view
      +schema: stg
    intermediate:
      +materialized: view
      +schema: int
    marts:
      core:
        +materialized: table
        +schema: core
      business:
        +materialized: table
        +schema: business

snapshots:
  transform:
    +target_schema: snapshots

tests:
  olist_wh_transform:
    +store_failures: true
    +schema: test_failures     # failed rows written to dev_test_failures schema